version: "3" # composeファイルのバージョン
services:
  freeren: # サービス名
    container_name: freeren
    build:
      context: . # ビルドするコンテキストのパス
      dockerfile: ./build/go/Dockerfile # ビルドに使うDockerファイルのパス
    volumes: # マウントディレクトリ
      - ./src:/go/src/app
    hostname: localhost
    ports:
      - "${PORT:-8080}:${PORT:-8080}" # 環境変数 PORT を使用し、デフォルトは 4000 に設定
    environment:
      - PORT=${PORT:-8080} # コンテナ内の環境変数として設定
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - .env
    networks:
      - private-net

volumes:
  db-store:
    driver: local
networks:
  private-net:
    driver: bridge
